### ISSUE TITLE
User.get_stats() throws an error if no stars have been collected for a year

### ISSUE THREAD

**Issue by jokajak** [wimglenn/advent-of-code-data#85]
The source of the `https://adventofcode.com/{year}/leaderboard/self` does not include an `article` tag which causes an exception:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jokajak/.cache/pypoetry/virtualenvs/aoc-coTrba3t-py3.10/lib/python3.10/site-packages/aocd/models.py", line 113, in get_stats
    if soup.article.pre is None and "overall leaderboard" in soup.article.text:
AttributeError: 'NoneType' object has no attribute 'pre'
```

**Comment by wimglenn** [comment]
@jokajak  Fixed in [1.2.1](https://pypi.org/project/advent-of-code-data/1.2.1/). Thanks for the report!
